### PR TITLE
add namespaceOverride template to manifests

### PR DESCRIPTION
**Pull request by yellowmegaman**
This PR adds a way to override namespace for Haproxy helm chart if it is being used as dependency in another helm (umbrella) chart.

### CODE REVIEW

**Comment by dkorunic** [comment]
Thanks @yellowmegaman, but you haven't documented `namespaceOverride` in `values.yaml` anywhere. Can you do that please?

**Comment by yellowmegaman** [comment]
@dkorunic done. thanks for the hint!

**Comment by dkorunic** [comment]
I've fixed a thing or two in the PR branch. Will merge now.

**Comment by yellowmegaman** [comment]
Woot! Thank you! 🎉

**Comment by yellowmegaman** [comment]
Can we please have a release with it?

**Pull request merged**
