### PR TITLE
Reload and includes

### PR DESCRIPTION
**Pull request by Infusible**

### CODE REVIEW

**Comment by dkorunic** [comment]
Hey @Infusible , this is still in the queue for a merge, don't worry.

**Comment by Infusible** [comment]
thx, @dkorunic

**Comment by Infusible** [comment]
Hi, @dkorunic 
You may want to use the new features k8s instead of the initContainers?)
https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/

**Comment by Infusible** [comment]
Hi, any updates? :)

**Comment by dkorunic** [comment]
@Infusible Still pending a review, I haven't had the time to fully integrate this but I plan to do very soon.

**Comment by Infusible** [comment]
@dkorunic, thx

**Comment by dkorunic** [comment]
Sadly, still not mergeable due to CE and EE differences and ways we have refactored EE enterprise image.

**Comment by Infusible** [comment]
@dkorunic plz close
add add new features helm-charts PR 118

**Comment by dkorunic** [comment]
As requested, closing in favor of #118.

**Pull request closed without merging**
