### PR TITLE
feat(haproxy): additional metrics for HPA.

### PR DESCRIPTION
**Pull request by mugioka**
Hi team.

Since i want to configure [RPS metrics](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#autoscaling-on-multiple-metrics-and-custom-metrics) in HPA, we can configure additional metrics as additionalMetrics in this PR.

Signed-off-by: mugioka <okamugi0722@gmail.com>

### CODE REVIEW

**Comment by dkorunic** [comment]
@mugioka Your editor has made a bunch of unwarranted YAML reformatting, can you revert that please?

**Comment by mugioka** [comment]
@dkorunic 
> can you revert that please?

Oh, sorry.
I will do it.

**Comment by mugioka** [comment]
@dkorunic 
 I've reverted.

**Comment by dkorunic** [comment]
Great, LGTM.

**Comment by mugioka** [comment]
@dkorunic 
Hi.
When will the this change to add this feature be released?

**Pull request merged**
