### PR TITLE
daemonset.yaml and deployment.yaml template files have been modified to allow configuring metadata.annotations using values (fix issue #93)

### LINKED ISSUE #93: haproxy template files daemonset.yaml and deployment.yaml do not allow to configure metadata.annotations using values
Both daemonset.yaml and deployment.yaml template files do not allow to configure metadata.annotations using values.

What we have:

```yaml
metadata:
  name: {{ include "haproxy.fullname" . }}
  labels:
    {{- include "haproxy.labels" . | nindent 4 }}
spec:
```

What we expect:

```yaml
metadata:
  name: {{ include "haproxy.fullname" . }}
  labels:
    {{- include "haproxy.labels" . | nindent 4 }}
  {{- if .Values.deploymentAnnotations }}
  annotations:
{{ toYaml .Values.deploymentAnnotations | indent 4 }}
  {{- end }}
spec:
```

### PR DESCRIPTION
**Pull request by denismaggior8**
Please evaluate and merge my PR.

Thanks
Denis

Signed-off-by: Denis Maggiorotto <denis.maggiorotto@sunnyvale.it>

### CODE REVIEW

**Comment by dkorunic** [comment]
@denismaggior8 Thanks. Both daemonsetAnnotations and deploymentAnnotations can be merged into single podAnnotations value, as there is no need to have separate parameters. For instance, like this: https://github.com/haproxytech/helm-charts/blob/4bb0ec34ad710bac33238d4463c8446bc8d2a9ce/kubernetes-ingress/values.yaml#L153

**Comment by denismaggior8** [comment]
Hi @dkorunic and thanks for your follow up. 

In my case, what I need to do, is to put an annotation at Deployment (or DaemonSet) level, let me give you an example: I'm using this special controller [stakater/reloader](https://github.com/stakater/Reloader) to restart haproxy pods for every TLS secret change. To do so, I have to put  an annotation in the Deployment declaration, such as:

```yaml
kind: Deployment
metadata:
  annotations:
    secret.reloader.stakater.com/reload: "foo-secret"
spec:
  template: metadata:
```

I think this feature may benefit also in other scenarios.

**Comment by dkorunic** [comment]
@denismaggior8 There is not a doubt that we need pod annotations (HAProxy core Chart was in fact done as a bare minimum Chart that will get features added as needed), but again, we don't need *separate* labels for Deployment kind and *separate* for Daemonset kind, as the same parameter (podAnnotations, for instance) can be used for both and final YAML will be correct, since in final YAML bundle we emit either one of Daemonset kind or Deployment kind.
If you are unsure and/or not comfortable with this, I'll gladly rewrite your PR before merging.

**Comment by denismaggior8** [comment]
Ok, thanks! I've tried to implement what you suggested. Please have a look of my last commit 99f38dc and let me know. Please feel free to adjust my PR if I still missed something.

**Pull request merged**
