### PR TITLE
RELEASE/MINOR: haproxy: Tag release 1.7.2

### PR DESCRIPTION
**Pull request by dfry**
FIX for: BUG: haproxy: use subpath for mounting haproxy.cfg file only (#121)

### CODE REVIEW

**Review by dkorunic — COMMENTED** [review]
Please, never push changes that force a new release. That task is for project maintainers only.

**Comment by dkorunic** [comment]
Sorry @dfry, I can't approve this PR just to force a release.

**Comment by dfry** [comment]
Per the contribution guidelines, you seem to be asking for version bumps in the PR, apologies if I misunderstood.

https://github.com/haproxytech/helm-charts/blob/main/CONTRIBUTING.md#merge-approval-and-release-process

**Any change to a chart requires a version bump following semver principles**

Also, I would assume you would only merge a PR that you approved.

**Comment by dkorunic** [comment]
@dfry Absolutely, but version bumps are for us to determine if it makes sense and if there are enough changes to mandate a release. Note that if you do a version bump, we automatically get Helm Charts released -- and in this case it would make sense for us to throughly test first, given it's not just a subtle change. In any case thanks for the PR and sorry for the confusion.

**Comment by dfry** [comment]
@dkorunic thanks for the explanation.  Since I am unable to deploy haproxy with dataplaneapi without this fix, I may need to build a custom chart with my change depending on when you would foresee cutting a release.

So if you can give a rough estimate, that would help.

**Comment by dkorunic** [comment]
@dfry I would say mid-next week at most, until we finish all automated and perform some additional manual testing.

**Comment by dfry** [comment]
👍  @dkorunic

**Pull request closed without merging**
