### PR TITLE
added option to attach more volumes in order to add certificates as s…

### PR DESCRIPTION
**Pull request by xussof**
Now you can add more volumes to the release in order to attach for example a volume with secrets for the certificates

### CODE REVIEW

**Comment by dkorunic** [comment]
@xussof Sadly this PR has far too many issues to be merged immediately:
1. unwanted change from Deployment kind to DaemonSet kind by default
2. volumeMounts for haproxy-config is intentionally not being in values.yaml, as we do not want users to omit it and have HAProxy crash on start due to missing config. This change should be reverted.
3. Configurable map of secrets (.Values.volumes.secrets) is a great idea, but they should be all generated in some sane default directory such as /etc/ssl.
4. Documentation should be updated (with some examples) so that people know how to reference certificates in config: block.

**Comment by dkorunic** [comment]
@xussof Let me know if you want me to edit your PR or you want me to write a new PR and merge it cleanly.

**Comment by xussof** [comment]
You can edit my PR as you want. Great work, thanks!

**Comment by K9L1E** [comment]
Hi @dkorunic,
do you have any plans to resolve that conflict above and close that PR?
I would really appreciate that merge.
Thanks in advanced

**Comment by dkorunic** [comment]
@K9L1E This PR needs a rewrite so it's not just resolving conflict, but a careful rewrite. It is in the queue, I plan to get on that during next week presumably.

**Comment by dkorunic** [comment]
Resolved with PR #77 merge.

**Pull request closed without merging**
